sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - nasm
    - gcc-4.8
    - g++-4.8
language: d
d:
  - dmd
compiler:
  - gcc
script:
  - git --version
  - dmd --version
  - gcc --version
  - alias gcc="gcc-4.8"
  - gcc --version
  - g++ --version
  - alias g++="g++-4.8"
  - g++ --version
  - nasm -v
  - travis_retry make test
