sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - nasm
    - gcc-5.2
    - g++-5.2
language: d
d:
  - dmd
compiler:
  - gcc
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5.2" CC="gcc-5.2"; fi
script:
  - git --version
  - dmd --version
  - gcc --version
  - g++ --version
  - nasm -v
  - travis_retry make test
