sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - nasm
    - gcc-5
    - g++-5
language: d
d:
  - dmd
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
script:
  - git --version
  - dmd --version
  - gcc --version
  - g++ --version
  - nasm -v
  - travis_retry make test
